<?php

namespace Database\Seeders;

use App\Models\Inventory\Store;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StoresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stores')->delete();

        DB::insert("INSERT INTO stores (StockId, StockNameAr, StockNameEn, StockTyp, status, userEntry)
        VALUES (1,'تقنية المعلومات','IT','M',1,1),
        (2,'الندوة','WAMY','S',1,1),
        (11829,'مهند محمد علي محمد','Muhannad Mohammed Ali Mohammed','E',1,1),
        (11001,'د. صالح الوهيبي','Dr.Saleh bin Suleiman Al - Wahibi','E',1,1),
        (11002,'د. صالح بابعير','Dr.Saleh bin Ibrahim Baabeer','E',1,1),
        (11022,'ايوب محمد موسى','Ayoub Mohamed Ahmed Moussa','E',1,1),
        (11029,'انور العظيم مزمدار','Anwar al-Azim Amin al-Haq is extinct','E',1,1),
        (11035,'سلطان صالح الحسين','Sultan Saleh Ahmed Al Hussein','E',1,1),
        (11039,'احمد راكعين','Ahmed Rakeen','E',1,1),
        (11045,'عصام محمد عطية','Essam Mohammed Attieh','E',1,1),
        (11063,'بابكر مهدي خوجلي','Babeker Mahdi Khojaly Ibrahim','E',1,1),
        (11076,'انور سالم مدشل','Anwar Salem Ahmed Medchel','E',1,1),
        (11077,'بدر احمد النهاري','Badr Ahmed Mohammed Al Nahari','E',1,1),
        (11084,'محمد عبده بخيت','Mohamed Abdo Mohamed Bakhit','E',1,1),
        (11090,'ابراهيم جمعان جرمي','Ibrahim Jamaan Eid Jerami','E',1,1),
        (11093,'ابراهيم فاروق خليل ابوحجر','Ibrahim Farouk Khalil Abu Hajar','E',1,1),
        (11097,'خالد مانع مخاشن','Khaled Mana Makhashin','E',1,1),
        (11099,'سلطان صالح ثامر العتيبي','Sultan Saleh Thamer Al Otaibi','E',1,1),
        (11105,'علي محمد علي مصطفى','Ali Mohamed Mostafa','E',1,1),
        (11124,'عبدالمتين عبدالمنان','Abdulmutin Abdel Manaf','E',1,1),
        (11125,'عبدالقادر سعيد محسن الحميري','Abdulkader Saeed Mohsen Al-Humiri','E',1,1),
        (11150,'مصطفى كمال الدين سفير','Mustafa Kemal Safir El Din','E',1,1),
        (11151,'مهند اسماعيل العتيبي','Muhannad Ismail Al Otaibi','E',1,1),
        (11166,'حسن عبده كديش','Hassan Abdo Al-Kadish','E',1,1),
        (11171,'احمد بدرالدين السعيد','Ahmed Badr El Din Adnan Said','E',1,1),
        (11175,'رائد حسن ابوفارس','Raed Hassan Abu Fares','E',1,1),
        (11181,'علي احمد علي الحريري','Ali Ahmed Al Hariri','E',1,1),
        (11182,'محمد علي سعيد','Mohammed Ali Said','E',1,1),
        (11193,'ثابت محمد ثابت اليوسفي','Thabet Mohammed Thabet Al Yousifi','E',1,1),
        (11219,'ياسر امجد جزاع الكبيسي','Yasser Amjad Jazaa Abdul Razzaq','E',1,1),
        (11221,'د. محمد بن حسين الصري','Dr.Mohammed bin Hussein Al-Sari','E',1,1),
        (11254,'عبدالرحمن حسين صالح مثنى','Abdulrahman Hussein Saleh Muthanna','E',1,1),
        (11277,'عبدالله محمد الشريف','Abdullah Mohammed Omran Al Sharif','E',1,1),
        (11318,'د.علي محمد سعيد الحاج','Dr.Ali Mohammed Said Al Haj','E',1,1),
        (11320,'جميل عبدالمجيد أمير علي','Jamil Abdul Majeed Amir Ali','E',1,1),
        (11321,'إبراهيم محمد قاسم هزاع','Ibrahim Mohammed Qassem Hazza','E',1,1),
        (11333,'محمد محسن عوض العويني','Mohammed Mohsen Awad Al Owaini','E',1,1),
        (11338,'إبراهيم يحيى عبدالقوي اليافعي','Ibrahim Yahya Abdelkawi Yafei','E',1,1),
        (11373,'د.عبدالحميد بن يوسف المزروع','Dr. Abdul Hamid Bin Yusuf Al Mazroua','E',1,1),
        (11380,'ياسر محمد عبدالفتاح','Yasser Mohamed Abdel Fattah Awad','E',1,1),
        (11383,'صالح سعيد عبدالله بنوب','Saleh Saeed Abdullah Banoub','E',1,1),
        (11386,'عبدالرقيب عبدالغني الشلفي','Abdulraqeeb Abdul Ghani Ahmed Shalafi','E',1,1),
        (11402,'عبدالله أحمد علي الحريري','Abdullah Ahmed Ali Hariri','E',1,1),
        (11409,'مصطفى مطر عبدالله نمر','Mustafa Matar Abdullah Nimer','E',1,1),
        (11430,'عبداللطيف علي سيف حسن','Abdul Latif Ali Saif Hassan','E',1,1),
        (11450,'فيصل محمد عبده عامر','Faisal Mohammed Abdo Amer','E',1,1),
        (11455,'خالد محمد سعيد بانبيلة','Khaled Mohamed Said Banabilah','E',1,1),
        (11462,'د.عبد الكريم العبد الكريم','Dr. Abdul Karim Bin Abdullah Al-Abdul Karim','E',1,1),
        (11489,'نبيل محمد بافضل','Nabil Mohammed Ahmed Bafdal','E',1,1),
        (11513,'ماهر عبدالعزيز ريشان العوده','Maher Abdul Aziz Rishan return','E',1,1),
        (11522,'احمد عبدالله حمود سرحان','Ahmed Abdullah Hamoud Sarhan','E',1,1),
        (11547,'أحمد محمد علي إسماعيل','Ahmed Mohamed Ali Ismail','E',1,1),
        (11568,'علي عطية علي الزهراني','Ali Attieh Ali Al Zahrani','E',1,1),
        (11689,'مبارك زين العابدين يوسف','Mubarak Zine El Abidine Youssef','E',1,1),
        (11693,'هاشم ابوبكر محمد الجندان','Hashim Abu Bakr Mohammed Al - Jandan','E',1,1),
        (11695,'احمد خلف صالح العنزي','Ahmed Khalaf Saleh Al Enazi','E',1,1),
        (11718,'عبدالرحيم احمد باشميل','Abdel Rahim Ahmed Abdel Rahim Bashmil','E',1,1),
        (11723,'أيمن سمير سلمان منصور','Ayman Samir Salman Mansour','E',1,1),
        (11748,'سعود محسن صالح بالعبيد','Saud Mohsen Saleh slaves','E',1,1),
        (11754,'عمر اسماعيل ابوبكر','Omar Ismail Abu Bakr Adam','E',1,1),
        (11758,'صلاح احمد احمد ملهى','Salah Ahmed Ahmed Melhi','E',1,1),
        (11766,'محمد مبارك احمد النور','Mohamed Mubarak Ahmed El Nour','E',1,1),
        (11768,'عمار عبد عوض محيفوظ','Ammar Abdel Awad Ben Mahifouz','E',1,1),
        (11776,'احمد عبد الله الصبيح','Ahmed Abdullah Al - Subeeh','E',1,1),
        (11816,'اكثم محمود احمد ابوعصبة','Aktham Mahmoud Ahmed Abu Aseba','E',1,1),
        (11857,'هادي محمد ال هادي','Hadi Mohammed Abdo Al Hadi','E',1,1),
        (11870,'اسامه حسين سلامه عيادة','Osama Hussein Salama Clinic','E',1,1),
        (11871,'حازم محمد علي البسطويسي','Hazem Mohammed Ali Bastawisi','E',1,1),
        (11883,'نصر علي محمد عامر','Nasr Ali Mohammed Amer','E',1,1),
        (11899,'هائل غالب سيف','Hail Ghalib Saif','E',1,1),
        (11910,'عبدالله عبدالرحمن الشهراني','Abdullah Abdul Rahman Mohammed Al Shahrani','E',1,1),
        (11915,'حامد محمد أكورا','Hamid Mohammed Acura','E',1,1),
        (11916,'حسين بن عبدالعزيز الحسيني','Hussein bin Abdulaziz Al-Husseini','E',1,1),
        (11922,'عبدالله بن علي بن علي حملي','Abdullah bin Ali bin Ali Hamli','E',1,1),
        (11923,'عبداللطيف بن محمد بن عبدالله النجاشي','Abdul Latif bin Mohammed bin Abdullah Al Najashi','E',1,1),
        (11932,'عبدالإله عبداللطيف ناصر العبدالكريم','Abdul-Abdullatif Nasser Al-Abd Al-Karim','E',1,1),
        (11935,'اشرف احمد محمد علي','Ashraf Ahmed Mohamed Ali','E',1,1),
        (11937,'بندر بن فهد عيفان العنزي','Bandar bin Fahd Aifan Al - Anzi','E',1,1),
        (11941,'عبدالرحمن بن عبدالله بن مشرف العمري','Abdulrahman bin Abdullah bin Musharraf Omri','E',1,1),
        (11942,'عبدالله عبدالرحمن التمامي','Abdullah Al - Tamami','E',1,1),
        (11960,'عبدالمجيد القحطاني','Abdul Majeed Al-Qahtani','E',1,1),
        (11948,'عبدالله بن عبدالغني بن محمد الشهري','Abdullah bin Abdulghani bin Mohammed Al Shehri','E',1,1),
        (11950,'ابراهيم عبدالعزيز محمد التويجري','Ibrahim Abdul Aziz Mohammed Altwaijri','E',1,1),
        (11951,'فيصل بن سعد بن عبدالله بن جبر','Faisal bin Saad bin Abdullah bin Jabr','E',1,1),
        (11952,'اسامه بن ناصر بن عبدالعزيز العباد','Osama bin Nasser bin Abdulaziz Al - Abbad','E',1,1),
        (11956,'محمد راسل مصباح الدين فجر','Mohammed Musallabuddin Dawn','E',1,1),
        (11974,'عبدالعزيز الفالح','Abdulaziz Al-Faleh','E',1,1),
        (20042,'عبدالله احمد عبد الرحمن باعلوي','Abdullah Ahmed Abdul Rahman Baalawi','E',1,1),
        (20050,'سالم سعيد فرج باعوض','Salem Saeed Faraj Baoud','E',1,1),
        (20053,'حسين احمد سعيد العمودي','Hussein Ahmed Said Al Amoudi','E',1,1),
        (20059,'طارق محمد عبدالعزيز حليمه','Tariq Mohamed Abdel Aziz Halima','E',1,1),
        (20350,'عبدالله محمد صالح الصبحي','Abdullah Mohammed Saleh Al-Subhi','E',1,1),
        (11968,'مصعب الهويسين','Musab Al Huwaisin','E',1,1),
        (11977,'محمد عبده علي المخلافي','Muhammad Abdo Ali Al-Mikhlafi','E',1,1),
        (11971,'تميم حمد عبدالله الماجد','Tamim Hamad Abdullah Al Majed','E',1,1),
        (11991,'محمد عبدالله العطاس','Mohammed Abdullah Al-Attas','E',1,1),
        (11981,'خالد بن عبدالله بن عبدالعزيز الحسيني','Khalid bin Abdullah bin Abdulaziz Al-Hussaini','E',1,1),
        (11980,'سعد بن محمد بن حمد الحصيني','Saad bin Mohammed bin Hamad al-Husaini','E',1,1),
        (11996,'محمد الماضي','محمد الماضي','E',1,1),
        (11987,'فهد الهويشل','Fahad al hueshal','E',1,1),
        (11994,'سالم بن محمد بن سالم البران','Salem Muhammad Salem Al-Barran','E',1,1),
        (12007,'خالد موسى الزهراني','Khaled Musa Al-Zahrani','E',1,1),
        (12014,'رائد الصالح','Raed Al-Saleh','E',1,1),
        (12018,'فيصل سعد فهد الحيد','Faisal Saad Fahad Al-hed','E',1,1),
        (11992,'أحمد هاشم محمد العمري','Ahmed Hashem Mohammed Al-Amry','E',1,1),
        (12012,'فيصل يوسف عساف العساف','Faisal Yousef Assaf Al-Assaf','E',1,1),
        (11982,'محمد أحمد عبدالله رديني','Mohammed Ahmed Abdulla Rodainy','E',1,1),
        (11983,'علي عطية علي الزهراني','Ali Atya Ali Al-Zahrani','E',1,1),
        (12016,'عبدالله فهد عبدالله الحسين','Abdukka Fahad Abdulla Al-Hussin','E',1,1),
        (11975,'عبدالعزين ابراهيم عبدالله البرغش','Abdulaziz Ibraheem Abdulla Al-Bargash','E',1,1),
        (12017,'معاذ أحمد السيار','Moath Ahmed Al-sayyar','E',1,1),
        (12005,'عبدالعزيز صالح العواد','Abdulaziz Saleh Al-Awwad','E',1,1),
        (11966,'صالح عبدالله الشمراني','Saleh Abdulla Al-Shamrani','E',1,1),
        (11988,'أسامة محمد فقيه','Osama Mohammed Faqih','E',1,1),
        (11999,'عبدالعزيز محمد الجبرين','ABDULAZIZ MOHMMED ALJEBREEN','E',1,1),
        (12019,'محمد علي عبده رديني','Mohammed Ali Rodiny','E',1,1),
        (11998,'سطام سلمان العمري','sattam salman al-amri','E',1,1),
        (12013,'سلمان خالد حملي','Salman Khaled Hamli','E',1,1),
        (12020,'يوسف علي عيسى العريفي','Yousef Ali Eisaa Alarifi','E',1,1),
        (12004,'عبدالله محمد الأحمد','Abduallah Alahmad','E',1,1),
        (12001,'علي محمد سعيد الحاج','Ali Mohammed Saeed Al_Haj','E',1,1),
        (12023,'معتصم محمد علي الكباري','moatasem mohammed ali alkubari','E',1,1),
        (12021,'عبدالله عبدالمحسن عبدالله الزهراني','Abdullah Abdulmhsen Alzhrani','E',1,1),
        (12003,'عمر فهد المغذوي','OMAR FAHAD AL;MUGHATHAWI','E',1,1),
        (11997,'عبدالله محمد القرني','ABDULLAH MOHAMMED ALQARNI','E',1,1)");
    }
}
